### ISSUE TITLE
finalize design

### ISSUE THREAD

**Issue by inkthink** [inkthink/an-alt-ergodox-ez-layout#1]
![ergo-dox ez cmd](https://cloud.githubusercontent.com/assets/16294929/11881844/58fef964-a4d7-11e5-9722-0597e0326a2f.png)

**Comment by plgruener** [comment]
If I may ask: how did you produce this wonderful image? :D

**Comment by inkthink** [comment]
Using the [keyboard layout editor](http://www.keyboard-layout-editor.com/##@@_x:3.5&c=%233b3a3a&t=%23cccccc%3B&=%23%0A3&_x:10.5%3B&=*%0A8%3B&@_y:-0.875&x:2.5%3B&=%2F@%0A2&_x:1%3B&=%24%0A4&_x:8.5%3B&=%2F&%0A7&_x:1%3B&=%28%0A9%3B&@_y:-0.875&x:5.5%3B&=%25%0A5&_a:7%3B&=&_x:4.5%3B&=&_a:4%3B&=%5E%0A6%3B&@_y:-0.875&a:7&w:1.5%3B&=&_a:4%3B&=!%0A1&_x:14.5%3B&=%29%0A0&_a:7&w:1.5%3B&=%3B&@_y:-0.375&x:3.5&a:4%3B&=E&_x:10.5%3B&=I%3B&@_y:-0.875&x:2.5%3B&=W&_x:1%3B&=R&_x:8.5%3B&=U&_x:1%3B&=O%3B&@_y:-0.875&x:5.5%3B&=T&_a:7&h:1.5%3B&=&_x:4.5&h:1.5%3B&=&_a:4%3B&=Y%3B&@_y:-0.875&a:7&w:1.5%3B&=&_a:4%3B&=Q&_x:14.5%3B&=P&_a:7&w:1.5%3B&=%3B&@_y:-0.375&x:3.5&a:4%3B&=D&_x:10.5%3B&=K%3B&@_y:-0.875&x:2.5%3B&=S&_x:1%3B&=F&_x:8.5%3B&=J&_x:1%3B&=L%3B&@_y:-0.875&x:5.5%3B&=G&_x:6.5%3B&=H%3B&@_y:-0.875&a:7&w:1.5%3B&=&_a:4%3B&=A&_x:14.5%3B&=%2F:%0A%2F%3B&_a:7&w:1.5%3B&=%3B&@_y:-0.625&x:6.5&h:1.5%3B&=&_x:4.5&h:1.5%3B&=%3B&@_y:-0.75&x:3.5&a:4%3B&=C&_x:10.5%3B&=%3C%0A,%3B&@_y:-0.875&x:2.5%3B&=X&_x:1%3B&=V&_x:8.5%3B&=M&_x:1%3B&=%3E%0A.%3B&@_y:-0.875&x:5.5%3B&=B&_x:6.5%3B&=N%3B&@_y:-0.875&a:7&w:1.5%3B&=&_a:4%3B&=Z&_x:14.5%3B&=%3F%0A%2F%2F&_a:7&w:1.5%3B&=%3B&@_y:-0.375&x:3.5%3B&=&_x:10.5%3B&=%3B&@_y:-0.875&x:2.5%3B&=&_x:1%3B&=&_x:8.5%3B&=&_x:1%3B&=%3B&@_y:-0.75&x:0.5%3B&=&=&_x:14.5%3B&=&=%3B&@_r:30&rx:6.5&ry:4.25&y:-1&x:1%3B&=&=%3B&@_h:2%3B&=&_h:2%3B&=&=%3B&@_x:2%3B&=%3B&@_r:-30&rx:13&y:-1&x:-3%3B&=&=%3B&@_x:-3%3B&=&_h:2%3B&=&_h:2%3B&=%3B&@_x:-3%3B&=)

**Comment by inkthink** [comment]
Here's a link with the keyboard properties using Bamboo Texture: [as above](http://www.keyboard-layout-editor.com/##@_background_name=Bamboo&style=background-image%2F:%20url%28'%2F%2Fbg%2F%2Fwood%2F%2Fbamboo.jpg'%29%2F%3B&$$hashKey=0BZ%3B%3B&@_x:3.5&c=%233b3a3a&t=%23cccccc%3B&=%23%0A3&_x:10.5%3B&=*%0A8%3B&@_y:-0.875&x:2.5%3B&=%2F@%0A2&_x:1%3B&=$%0A4&_x:8.5%3B&=%2F&%0A7&_x:1%3B&=%28%0A9%3B&@_y:-0.875&x:5.5%3B&=%25%0A5&_a:7%3B&=&_x:4.5%3B&=&_a:4%3B&=%5E%0A6%3B&@_y:-0.875&a:7&w:1.5%3B&=&_a:4%3B&=!%0A1&_x:14.5%3B&=%29%0A0&_a:7&w:1.5%3B&=%3B&@_y:-0.375&x:3.5&a:4%3B&=E&_x:10.5%3B&=I%3B&@_y:-0.875&x:2.5%3B&=W&_x:1%3B&=R&_x:8.5%3B&=U&_x:1%3B&=O%3B&@_y:-0.875&x:5.5%3B&=T&_a:7&h:1.5%3B&=&_x:4.5&h:1.5%3B&=&_a:4%3B&=Y%3B&@_y:-0.875&a:7&w:1.5%3B&=&_a:4%3B&=Q&_x:14.5%3B&=P&_a:7&w:1.5%3B&=%3B&@_y:-0.375&x:3.5&a:4%3B&=D&_x:10.5%3B&=K%3B&@_y:-0.875&x:2.5%3B&=S&_x:1%3B&=F&_x:8.5%3B&=J&_x:1%3B&=L%3B&@_y:-0.875&x:5.5%3B&=G&_x:6.5%3B&=H%3B&@_y:-0.875&a:7&w:1.5%3B&=&_a:4%3B&=A&_x:14.5%3B&=%2F:%0A%2F%3B&_a:7&w:1.5%3B&=%3B&@_y:-0.625&x:6.5&h:1.5%3B&=&_x:4.5&h:1.5%3B&=%3B&@_y:-0.75&x:3.5&a:4%3B&=C&_x:10.5%3B&=%3C%0A,%3B&@_y:-0.875&x:2.5%3B&=X&_x:1%3B&=V&_x:8.5%3B&=M&_x:1%3B&=%3E%0A.%3B&@_y:-0.875&x:5.5%3B&=B&_x:6.5%3B&=N%3B&@_y:-0.875&a:7&w:1.5%3B&=&_a:4%3B&=Z&_x:14.5%3B&=%3F%0A%2F%2F&_a:7&w:1.5%3B&=%3B&@_y:-0.375&x:3.5%3B&=&_x:10.5%3B&=%3B&@_y:-0.875&x:2.5%3B&=&_x:1%3B&=&_x:8.5%3B&=&_x:1%3B&=%3B&@_y:-0.75&x:0.5%3B&=&=&_x:14.5%3B&=&=%3B&@_r:30&rx:6.5&ry:4.25&y:-1&x:1%3B&=&=%3B&@_h:2%3B&=&_h:2%3B&=&=%3B&@_x:2%3B&=%3B&@_r:-30&rx:13&y:-1&x:-3%3B&=&=%3B&@_x:-3%3B&=&_h:2%3B&=&_h:2%3B&=%3B&@_x:-3%3B&=)

**Comment by inkthink** [comment]
[filled in](http://www.keyboard-layout-editor.com/##@_name=Ergo-Dox-EZ%20⌘&notes=%230076ff%20Media%20Layer%0A%23b81b24%20FN%20layer%0A%233ab81b%20Keypad%20layer%0A%23737373%20Shift%20or%20CAPS%20Lock&background_name=Bamboo&style=background-image%2F:%20url%28'%2F%2Fbg%2F%2Fwood%2F%2Fbamboo.jpg'%29%2F%3B%3B%3B&@_x:3.5&c=%232b2c2e&t=%23737373%0A%23fffffff%0A%0A%23c9aa6e%0A%0A%0A%0A%230076ff%0A%23b81b24%0A%0A%233ab81b&fa@:0&:0&:0&:1&:0&:0&:0&:0&:1&:0&:2%3B%3B&=%23%0A3%0A%0A8%0A%0A%0A%0A%3Ci%20class%2F='kb%20kb-logo-windows-8'%3E%3C%2F%2Fi%3E%0AF3%0A%0A%23&_x:10.5&t=%23737373%0A%23fffffff%0A%0A%0A%0A%0A%0A%230076ff%0A%23b81b24%3B&=*%0A8%0A%0A%0A%0A%0A%0A%3Ci%20class%2F='kb%20kb-Multimedia-Play-Pause'%3E%3C%2F%2Fi%3E%0AF8%3B&@_y:-0.875&x:2.5&t=%23737373%0A%23fffffff%0A%0A%23c9aa6e%0A%0A%0A%0A%230076ff%0A%23b81b24%0A%0A%233ab81b%3B&=%2F@%0A2%0A%0A7%0A%0A%0A%0A%3Ci%20class%2F='kb%20kb-Unicode-Screen-Bright'%3E%3C%2F%2Fi%3E%0AF2%0A%0A%2F@&_x:1%3B&=$%0A4%0A%0A9%0A%0A%0A%0A%3Ci%20class%2F='fa%20fa-th'%3E%3C%2F%2Fi%3E%0AF4%0A%0A$&_x:8.5&t=%23737373%0A%23fffffff%0A%0A%0A%0A%0A%0A%230076ff%0A%23b81b24%3B&=%2F&%0A7%0A%0A%0A%0A%0A%0A%3Ci%20class%2F='kb%20kb-Multimedia-Rewind'%3E%3C%2F%2Fi%3E%0AF7&_x:1%3B&=%28%0A9%0A%0A%0A%0A%0A%0A%3Ci%20class%2F='kb%20kb-Multimedia-FastForwar'%3E%3C%2F%2Fi%3E%0AF9%3B&@_y:-0.875&x:5.5&t=%23737373%0A%23fffffff%0A%0A%23c9aa6e%0A%0A%0A%0A%0A%23b81b24%0A%0A%233ab81b%3B&=%25%0A5%0A%0A0%0A%0A%0A%0A%0AF5%0A%0A%7B&_t=%23737373%0A%23fffffff%0A%0A%23c9aa6e%3B&=%2F_%0A-%0A%0A%2F=&_x:4.5&t=%23737373%0A%23fffffff%3B&=+%0A%2F=&_t=%23737373%0A%23fffffff%0A%0A%0A%0A%0A%0A%0A%23b81b24%0A%0A%233ab81b&fa@:0&:0&:0&:1&:0&:0&:0&:0&:1%3B%3B&=%5E%0A6%0A%0A%0A%0A%0A%0A%0AF6%0A%0A%7D%3B&@_y:-0.875&t=%23737373%0A%23fffffff%0A%0A%23c9aa6e%0A%0A%0A%0A%0A%0A%23b81b24%0A%233ab81b&fa@:0&:1&:0&:1&:0&:0&:0&:0&:1&:0&:1%3B&w:1.5%3B&=%0A~L1%0A%0A-L2%0A%0A%0A%0A%0A%0AFN%0A+L2&_t=%23737373%0A%23fffffff%0A%0A%23c9aa6e%0A%0A%0A%0A%230076ff%0A%23b81b24%0A%0A%233ab81b&fa@:0&:0&:0&:1&:0&:0&:0&:0&:1&:0&:2%3B%3B&=!%0A1%0A%0A6%0A%0A%0A%0A%3Ci%20class%2F='kb%20kb-Unicode-Screen-Dim'%3E%3C%2F%2Fi%3E%0AF1%0A%0A!&_x:14.5&t=%23737373%0A%23fffffff%0A%0A%0A%0A%0A%0A%230076ff%0A%23b81b24%0A%0A%233ab81b&fa@:0&:0&:0&:1&:0&:0&:0&:0&:1%3B%3B&=%29%0A0%0A%0A%0A%0A%0A%0A%3Ci%20class%2F='kb%20kb-Multimedia-Mute-4'%3E%3C%2F%2Fi%3E%0AF10%0A%0A+&_t=%23737373%0A%0A%0A%0A%0A%0A%0A%230076ff%0A%23b81b24&w:1.5%3B&=%0A%0A%0A%0A%0A%0A%3Ci%20class%2F='kb%20kb-Tab-1'%3E%3C%2F%2Fi%3E%0A%3Ci%20class%2F='kb%20kb-Multimedia-Volume-Down-2'%3E%3C%2F%2Fi%3E%0AF11%3B&@_y:-0.375&x:3.5&t=%23737373%0A%0A%0A%23c9aa6e%3B&=E%0A%0A%0Au&_x:10.5&t=%23737373%0A%0A%0A%0A%0A%0A%0A%0A%0A%0A%233ab81b&fa@:0&:0&:0&:1&:0&:0&:0&:0&:1&:0&:2%3B%3B&=I%0A%0A%0A%0A%0A%0A%0A%0A%0A%0A5%3B&@_y:-0.875&x:2.5&t=%23737373%0A%0A%0A%23c9aa6e%3B&=W%0A%0A%0Ao&_x:1%3B&=R%0A%0A%0Ai&_x:8.5&t=%23737373%0A%0A%0A%0A%0A%0A%0A%0A%0A%0A%233ab81b%3B&=U%0A%0A%0A%0A%0A%0A%0A%0A%0A%0A4&_x:1%3B&=O%0A%0A%0A%0A%0A%0A%0A%0A%0A%0A6%3B&@_y:-0.875&x:5.5&t=%23737373%0A%0A%0A%23c9aa6e%0A%0A%0A%0A%0A%0A%0A%233ab81b%3B&=T%0A%0A%0Ap%0A%0A%0A%0A%0A%0A%0A%5B&_t=%23737373%0A%23fffffff%0A%0A%23c9aa6e%0A%0A%0A%0A%0A%0A%0A%233ab81b&h:1.5%3B&=~%0A%60%0A%0A'%0A%0A%0A%0A%0A%0A%0A~&_x:4.5&t=%23737373%0A%23fffffff%0A%0A%0A%0A%0A%0A%0A%0A%0A%233ab81b&f:3&h:1.5%3B&=%22%0A'%0A%0A%0A%0A%0A%0A%0A%0A%0A%22&_t=%23737373%0A%0A%0A%0A%0A%0A%0A%0A%0A%0A%233ab81b&f:3%3B&=Y%0A%0A%0A%0A%0A%0A%0A%0A%0A%0A%5D%3B&@_y:-0.875&t=%23b81b24%0A%0A%0A%0A%0A%0A%23c9aa6e&a:5&fa@:1%3B&w:1.5%3B&=Teensy%0A%0A%0A%0A%0A%0AL%20%3Ci%20class%2F='kb%20kb-Symbol-Keyboard'%3E%3C%2F%2Fi%3E&_t=%23737373%0A%0A%0A%23c9aa6e%0A%0A%0A%0A%0A%0A%0A%233ab81b&a:4&fa@:0&:0&:0&:1&:0&:0&:0&:0&:0&:0&:2%3B%3B&=Q%0A%0A%0Ay%0A%0A%0A%0A%0A%0A%0A%7C&_x:14.5&t=%23737373%0A%0A%0A%0A%0A%0A%0A%0A%0A%0A%233ab81b&f:3%3B&=P%0A%0A%0A%0A%0A%0A%0A%0A%0A%0A-&_t=%23737373%0A%23ffffff%0A%0A%0A%0A%0A%0A%230076ff%0A%23b81b24&fa@:0&:0&:0&:1&:0&:0&:0&:0&:1%3B&w:1.5%3B&=%7C%0A%5C%0A%0A%0A%0A%0A%0A%3Ci%20class%2F='kb%20kb-Multimedia-Volume-Up-2'%3E%3C%2F%2Fi%3E%0AF12%3B&@_y:-0.375&x:3.5&t=%23737373%0A%0A%0A%23c9aa6e%3B&=D%0A%0A%0Ak&_x:10.5&t=%23737373%0A%0A%0A%0A%0A%0A%0A%0A%0A%0A%233ab81b&fa@:0&:0&:0&:1&:0&:0&:0&:0&:1&:0&:2%3B%3B&=K%0A%0A%0A%0A%0A%0A%0A%0A%0A%0A2%3B&@_y:-0.875&x:2.5&t=%23737373%0A%0A%0A%23c9aa6e%3B&=S%0A%0A%0Aj&_x:1%3B&=F%0A%0A%0Al&_x:8.5&t=%23737373%0A%0A%0A%0A%0A%0A%0A%0A%0A%0A%233ab81b%3B&=J%0A%0A%0A%0A%0A%0A%0A%0A%0A%0A1&_x:1%3B&=L%0A%0A%0A%0A%0A%0A%0A%0A%0A%0A3%3B&@_y:-0.875&x:5.5&t=%23737373%0A%0A%0A%23c9aa6e%0A%0A%0A%0A%0A%0A%0A%233ab81b%3B&=G%0A%0A%0A%2F%3B%0A%0A%0A%0A%0A%0A%0A%28&_x:6.5&t=%23737373%0A%0A%0A%0A%0A%0A%0A%0A%0A%0A%233ab81b&f:3%3B&=H%0A%0A%0A%0A%0A%0A%0A%0A%0A%0A%29%3B&@_y:-0.875&t=%2337ff00&a:7&fa@:5%3B&w:1.5%3B&=%3Ci%20class%2F='fa%20fa-calculator'%3E&_t=%23737373%0A%0A%0A%23c9aa6e%0A%0A%0A%0A%0A%0A%0A%233ab81b&a:4&fa@:0&:0&:0&:1&:0&:0&:0&:0&:0&:0&:2%3B%3B&=A%0A%0A%0Ah%0A%0A%0A%0A%0A%0A%0A%2F:&_x:14.5&t=%23737373%0A%23fffffff%0A%0A%0A%0A%0A%0A%0A%0A%0A%233ab81b&f:3%3B&=%2F:%0A%2F%3B%0A%0A%0A%0A%0A%0A%0A%0A%0A*&_t=%23266fd4&a:7&fa@:6%3B&w:1.5%3B&=%3Ci%20class%2F='fa%20fa-gamepad'%3E%3C%2F%2Fi%3E%3B&@_y:-0.625&x:6.5&t=%23737373%0A%23fffffff%0A%0A%23c9aa6e%0A%0A%0A%0A%0A%0A%0A%233ab81b&a:4&fa@:0&:0&:0&:1&:0&:0&:0&:0&:0&:0&:2%3B&h:1.5%3B&=%7B%0A%5B%0A%0A'%0A%0A%0A%0A%0A%0A%0A'&_x:4.5&t=%23737373%0A%23fffffff%0A%0A%0A%0A%0A%0A%0A%0A%0A%233ab81b&f:3&h:1.5%3B&=%7D%0A%5D%0A%0A%0A%0A%0A%0A%0A%0A%0A'%3B&@_y:-0.75&x:3.5&t=%23737373%3B&=C&_x:10.5&t=%23737373%0A%23fffffff%3B&=%3C%0A,%3B&@_y:-0.875&x:2.5&t=%23737373%3B&=X&_x:1%3B&=V&_x:8.5&t=%23737373%0A%0A%0A%0A%0A%0A%0A%0A%0A%233ab81b%0A%233ab81b&fa@:0&:0&:0&:1&:0&:0&:0&:0&:0&:1&:1%3B%3B&=M%0A%0A%0A%0A%0A%0A%0A%0A%0A00%0A0&_x:1&t=%23737373%0A%23fffffff%3B&=%3E%0A.%3B&@_y:-0.875&x:5.5&t=%23737373%0A%0A%0A%0A%0A%0A%0A%0A%0A%0A%233ab81b&fa@:0&:0&:0&:1&:0&:0&:0&:0&:0&:1&:2%3B%3B&=B%0A%0A%0A%0A%0A%0A%0A%0A%0A%0A%3C&_x:6.5&f:3%3B&=N%0A%0A%0A%0A%0A%0A%0A%0A%0A%0A%3E%3B&@_y:-0.875&t=%23737373%0A%23fffffc%0A%0A%0A%0A%0A%0A%0A%23b81b24&w:1.5%3B&=%0A⇧%0A%0A%0A%0A%0A%0A%0A⇪&_t=%23737373%0A%0A%0A%0A%0A%0A%0A%0A%0A%0A%233ab81b&f:3%3B&=Z%0A%0A%0A%0A%0A%0A%0A%0A%0A%0A%3F&_x:14.5&t=%23737373%0A%23fffffff%3B&=%3F%0A%2F%2F&_t=%23737373%0A%23fefefe%0A%0A%0A%0A%0A%0A%0A%23b81b24&w:1.5%3B&=%0A⇧%0A%0A%0A%0A%0A%0A%0A⇪%3B&@_y:-0.375&x:3.5&t=%23737373%0A%23fffffff%3B&=%0A%3Ci%20class%2F='mss%20mss-Unicode-Page-Up-5'%3E%3C%2F%2Fi%3E&_x:10.5&t=%23737373%0A%23fffffff%0A%0A%0A%0A%0A%0A%230076ff%0A%23b81b24%3B&=%0A%3Ci%20class%2F='kb%20kb-Arrows-Up'%3E%3C%2F%2Fi%3E%0A%0A%0A%0A%0A%0A%3Ci%20class%2F='fa%20fa-hand-o-up'%3E%3C%2F%2Fi%3E%0A%3Ci%20class%2F='kb%20kb-Unicode-Page-Up-3'%3E%3C%2F%2Fi%3E%3B&@_y:-0.875&x:2.5&t=%23737373%0A%23fffffff%3B&=%0A%3Ci%20class%2F='mss%20mss-Unicode-Page-Down-5'%3E%3C%2F%2Fi%3E&_x:1%3B&=%0A%3Ci%20class%2F='kb%20kb-Arrows-Bottom-2'%3E%3C%2F%2Fi%3E&_x:8.5&t=%23737373%0A%23fffffff%0A%0A%0A%0A%0A%0A%230076ff%0A%23b81b24%3B&=%0A%3Ci%20class%2F='kb%20kb-Arrows-Left'%3E%3C%2F%2Fi%3E%0A%0A%0A%0A%0A%0A%3Ci%20class%2F='fa%20fa-hand-o-left'%3E%3C%2F%2Fi%3E%0A%3Ci%20class%2F='kb%20kb-Arrows-Top-2'%3E%3C%2F%2Fi%3E&_x:1&t=%23737373%0A%0A%0A%0A%0A%0A%0A%230076ff%0A%23b81b24%3B&=%0A%3Ci%20class%2F='kb%20kb-Arrows-Down'%3E%3C%2F%2Fi%3E%0A%0A%0A%0A%0A%0A%3Ci%20class%2F='fa%20fa-hand-o-down'%3E%3C%2F%2Fi%3E%0A%3Ci%20class%2F='mss%20mss-Unicode-Page-Down-5'%3E%3C%2F%2Fi%3E%3B&@_y:-0.75&x:0.5&t=%23737373%0A%23fffffff%0A%0A%0A%0A%0A%0A%230076ff%0A%23b81b24&fa@:0&:0&:0&:1&:0&:0&:0&:0&:1%3B%3B&=%0A%3Ci%20class%2F='mss%20mss-Unicode-Escape-3'%3E%3C%2F%2Fi%3E%0A%0A%0A%0A%0A%0A%3Ci%20class%2F='kb%20kb-Multimedia-Eject'%3E%3C%2F%2Fi%3E%0A⌥⌘%3Ci%20class%2F='mss%20mss-Unicode-Escape-3'%3E%3C%2F%2Fi%3E&_t=%23cccccc%0A%23fffffff%3B&=%0A%3Ci%20class%2F='kb%20kb-Arrows-Top-1'%3E%3C%2F%2Fi%3E&_x:14.5&t=%23737373%0A%23fffffff%0A%0A%0A%0A%0A%0A%230076ff%0A%23b81b24&fa@:0&:0&:0&:1&:0&:0&:0&:0&:2%3B%3B&=%0A%3Ci%20class%2F='kb%20kb-Arrows-Up'%3E%3C%2F%2Fi%3E%0A%0A%0A%0A%0A%0A%3Ci%20class%2F='fa%20fa-hand-o-right'%3E%3C%2F%2Fi%3E%0A%3Ci%20class%2F='kb%20kb-Arrows-Bottom-2'%3E%3C%2F%2Fi%3E&_t=%23b81b24%0A%23fcfcfc%3B&=%0Aright-click%3B&@_r:30&rx:6.5&ry:4.25&y:-1&x:1&t=%23ffffff&a:7&fa@:1%3B%3B&=MEH&=⌃%3B&@_t=%23737373%0A%23fffffff%0A%0A%0A%0A%0A%0A%0A%23b81b24&a:4&h:2%3B&=%0A%3Ci%20class%2F='mss%20mss-Unicode-BackSpace-DeleteLeft-Big-2'%3E%3C%2F%2Fi%3E%0A%0A%0A%0A%0A%0A%0A%3Ci%20class%2F='mss%20mss-Unicode-DeleteRight-Big-2'%3E%3C%2F%2Fi%3E&_t=%23fcfafa&a:7&h:2%3B&=HYPER&_t=%23ffffff&f:3%3B&=⌥%3B&@_x:2&f:3%3B&=⌘%3B&@_r:-30&rx:13&y:-1&x:-3&f:3%3B&=⌃&_t=%23faf7f8%0A%0A%230076ff&a:6%3B&=%0A%0Aleft-click%3B&@_x:-3&t=%23ffffff&a:7&f:3%3B&=⌥&_fa@:8%3B&h:2%3B&=␠&_t=%23fffafa&f:3&h:2%3B&=%3Ci%20class%2F='kb%20kb-Return-2'%3E%3C%2F%2Fi%3E%3B&@_x:-3&t=%23ffffff&f:3%3B&=⌘)

**Comment by inkthink** [comment]
![2-layer simplification](https://cloud.githubusercontent.com/assets/16294929/12039975/eb7d6ca8-ae32-11e5-8f61-acf5cc0541c2.jpg)

**Comment by inkthink** [comment]
![2-layer ergodox](https://cloud.githubusercontent.com/assets/16294929/12040453/1ea11b26-ae37-11e5-8105-2cd75255c947.jpg)
2 layer simplification (mouse keys on FN/# layer)
